### ISSUE TITLE
如何添加规划概念？

### ISSUE THREAD

**Issue by hereiszhl** [tsinghua-fib-lab/DRL-urban-planning#11]
作者你好，我查看了代码和论文之后并未找到明确的上传规划概念的位置。似乎规划概念是需要添加在初始的底图中么？如果是的话，请问是以什么样的形式添加呢？是在底图制作的过程中添加线段或点么？

**Comment by DavyMorgan** [comment]
你好，规划概念是在初始的底图中添加线段或者点，可以参考urban_planning/cfg/test_data/real/hlg/init_plan_hlg_concept.pickle文件中的概念添加方式，dict中有一个单独的'concept'字段
