### ISSUE TITLE
更换底图后训练

### ISSUE THREAD

**Issue by yutong12** [tsinghua-fib-lab/DRL-urban-planning#12]
![image](https://github.com/tsinghua-fib-lab/DRL-urban-planning/assets/59248260/fc3aa46e-b194-4546-aad8-a71858116fb9)
我尝试利用extra/explore.ipynb构建自己的底图，我们选用的是中国南京的一个小型社区，但是按照示例提供的方式进行构建后，发现打包出来的pickle文件直接trian.py时会报错，debug发现错误urban_planning/envs/city.py中，将其与笔记本保持一致后能顺利完成环境构建，
然而 开始训练时 每个worker都提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action (228) when the mask is ([False False False ... False False False])
我检查了我的底图设置和参数信息，不知道应该在哪里改动什么参数以解决这个问题，
期望得到您的帮助！

**Comment by DavyMorgan** [comment]
我上传了更新的extra/explore.ipynb，使用更新版的生成pickle文件即可。另外，还需要根据地图修改objectives.yaml文件。

**Comment by yutong12** [comment]
hi，obejctives.yaml里面的规划修改是否有什么技巧？我照着hlg里面的设计进行修改，由于我的地图面积是hlg面积的六分之一 我尝试里面所有值缩小了六倍 但仍然报错 提示似乎是智能体采取的步骤不满足要求，无法成功训练

**Comment by yutong12** [comment]
更新后问题已经解决了 谢谢

**Comment by github-wgz** [comment]
您好，我也尝试利用更新后的extra/explore.ipynb构建自己的底图，选取了学校内部分地区进行尝试，成功得到pickle文件，但是接下来运行trian.py时会报错，同样的错误也出现在urban_planning/envs/city.py中，提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action when the mask is ([False False False ... False False False])，尝试对yaml文件中的配置信息进行修改后出现错误信息：（1）IndexError: index 1602 is out of bounds for axis 0 with size 288 ；（2）Actions took before becoming infeasible: [({'type': 4, 'x': 0.5, 'y': 0.5, 'area': 2000.0, 'length': 160.0, 'width': 40.0, 'height': 40.0, 'rect': 1.0, 'eqi': 1.0, 'sc': 1.0}, 262)] 。
        之后又尝试直接利用文件夹中的init_plan_huizhou.pickle得到规划结果，也出现了相同的问题，所以想请教您最后是如何解决这个问题，十分期望得到您的帮助！

**Comment by linniao** [comment]
您好，我也尝试利用更新后的extra/explore.ipynb构建自己的底图，选取了学校内部分地区进行尝试，成功得到pickle文件，但是接下来运行trian.py时会报错，同样的错误也出现在urban_planning/envs/city.py中，提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action when the mask is ([False False False ... False False False])，尝试对yaml文件中的配置信息进行修改后出现错误信息：（1）IndexError: index 1602 is out of bounds for axis 0 with size 288 ；（2）Actions took before becoming infeasible: [({'type': 4, 'x': 0.5, 'y': 0.5, 'area': 2000.0, 'length': 160.0, 'width': 40.0, 'height': 40.0, 'rect': 1.0, 'eqi': 1.0, 'sc': 1.0}, 262)] 。
    之后又尝试直接利用文件夹中的init_plan_huizhou.pickle得到规划结果，也出现了相同的问题，所以想请教您最后是如何解决这个问题，十分期望得到您的帮助！

**Comment by linniao** [comment]
您好，我也尝试利用更新后的extra/explore.ipynb构建自己的底图，选取了学校内部分地区进行尝试，成功得到pickle文件，
但是接下来运行trian.py时会报错，同样的错误也出现在urban_planning/envs/city.py中，提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action when the mask is ([False False False ... False False False])，尝试对yaml文件中的配置信息进行修改后出现错误信息：（1）IndexError: index 1602 is out of bounds for axis 0 with size 288 ；（2）Actions took before becoming infeasible: [({'type': 4, 'x': 0.5, 'y': 0.5, 'area': 2000.0, 'length': 160.0, 'width': 40.0, 'height': 40.0, 'rect': 1.0, 'eqi': 1.0, 'sc': 1.0}, 262)] 。
    之后又尝试直接利用文件夹中的init_plan_huizhou.pickle得到规划结果，也出现了相同的问题，所以想请教您最后是如何解决这个问题，十分期望得到您的帮助！

**Comment by linniao** [comment]
您好，我也尝试利用更新后的extra/explore.ipynb构建自己的底图，选取了学校内部分地区进行尝试，成功得到pickle文件，
但是接下来运行trian.py时会报错，同样的错误也出现在urban_planning/envs/city.py中，提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action when the mask is ([False False False ... False False False])，尝试对yaml文件中的配置信息进行修改后出现错误信息：（1）IndexError: index 1602 is out of bounds for axis 0 with size 288 ；（2）Actions took before becoming infeasible: [({'type': 4, 'x': 0.5, 'y': 0.5, 'area': 2000.0, 'length': 160.0, 'width': 40.0, 'height': 40.0, 'rect': 1.0, 'eqi': 1.0, 'sc': 1.0}, 262)] 。
    之后又尝试直接利用文件夹中的init_plan_huizhou.pickle得到规划结果，也出现了相同的问题，所以想请教您最后是如何解决这个问题，十分期望得到您的帮助！

**Comment by github-wgz** [comment]
您好，我也尝试利用更新后的extra/explore.ipynb构建自己的底图，选取了学校内部分地区进行尝试，成功得到pickle文件，但是接下来运行trian.py时会报错，同样的错误也出现在urban_planning/envs/city.py中，提示错误信息：urban_planning.envs.city.InfeasibleActionError: Infeasible action when the mask is ([False False False ... False False False])，尝试对yaml文件中的配置信息进行修改后出现错误信息：（1）IndexError: index 1602 is out of bounds for axis 0 with size 288 ；（2）Actions took before becoming infeasible: [({'type': 4, 'x': 0.5, 'y': 0.5, 'area': 2000.0, 'length': 160.0, 'width': 40.0, 'height': 40.0, 'rect': 1.0, 'eqi': 1.0, 'sc': 1.0}, 262)] 。
之后又尝试直接利用文件夹中的init_plan_huizhou.pickle得到规划结果，也出现了相同的问题，所以想请教您最后是如何解决这个问题，十分期望得到您的帮助！
