### ISSUE TITLE
Actions took before failing to place land use

### ISSUE THREAD

**Issue by cleverwade** [tsinghua-fib-lab/DRL-urban-planning#16]
感谢你的贡献！
我在尝试使用自己的数据的时候，遇到了如下问题：Intersection is not corner or within edge和Actions took before failing to place land use，我想请教一下这个错误是如何发生的？是因为我的数据不符合规范吗？还是因为我的规划计与社区尺寸不合适？
希望能够回复

**Comment by DavyMorgan** [comment]
根据您的描述来看，应该是数据差异导致的错误，您可以参考HLG和DHM两个社区的数据格式来进行修改或调整

**Comment by cleverwade** [comment]
感谢你的回复！我似乎已经找到了问题所在和解决方案。
原因：我想要通过包含道路的shp文件直接生成训练数据，但是似乎由于数据容差的问题，导致坐标点在1e-10精度左右出现了没有对齐的情况，我目前已经通过一定的方式解决了这个问题。

**Comment by gdjmck** [comment]
> 感谢你的回复！我似乎已经找到了问题所在和解决方案。 原因：我想要通过包含道路的shp文件直接生成训练数据，但是似乎由于数据容差的问题，导致坐标点在1e-10精度左右出现了没有对齐的情况，我目前已经通过一定的方式解决了这个问题。

请问如何解决容差问题的呢，我试了把原始数据的精度统一为小数点后一位，但是由于图形是任意斜率的，还是会出现新的顶点是会有容差问题。另外还对新增的顶点做了snap，也没有完全解决容差问题
