### ISSUE TITLE
about GPU acceleration

### ISSUE THREAD

**Issue by gallexy** [tsinghua-fib-lab/DRL-urban-planning#17]
感谢开源这个项目，获益良多！
跑了几遍这个程序，有一点比较好奇：好像训练中大多计算没有利用GPU加速，
反而有些代码强制使用cpu运算，如下：
with to_cpu(*self.sample_modules)
不知是什么缘故。是专门这样设计的吗？

**Comment by DavyMorgan** [comment]
您好，我们在训练模型更新其参数时使用GPU，而在与环境交互收集trajectory时使用CPU，这是根据运算并行程度来决定的。

**Comment by zi-v512** [comment]
你好，请问程序对显存要求大吗，我正在考虑配5080还是4090比较合适，希望能得到回复！感谢
