### ISSUE TITLE
Keyerror with the demo scripts

### ISSUE THREAD

**Issue by Kevin-Lee1299** [tsinghua-fib-lab/DRL-urban-planning#18]
Thanks a lot for your share of such an excellent project!

I run the evaluate scripts and got the output data,
but when i use demo script to visualize the plan,a key Error occurs:

KeyError: 'best_plans'
![image](https://github.com/user-attachments/assets/145d5e46-25ea-410b-bb91-d161d5946a71)

**Comment by gallexy-liu** [comment]
应该是best.p不对，调试一下，看看pickle.load之后结构

**Comment by Kevin-Lee1299** [comment]
![image](https://github.com/user-attachments/assets/5079f79f-522c-479e-9db2-036ba8021fdb)
如截图中所示，best.p中没有best_plans数据，导致无法获得gdf

**Comment by Kevin-Lee1299** [comment]
models文件夹下的best.p文件是我执行下面命令时生成的：
python3 -m urban_planning.train_ga --cfg hlg --global_seed 111

在执行具体的eval命令时，只在plan文件夹下获得了paln.p文件：

python3 -m urban_planning.eval --cfg hlg --global_seed 111 --agent rule-centralized
python3 -m urban_planning.eval --cfg hlg --global_seed 111 --agent rule-decentralized
python3 -m urban_planning.eval --cfg hlg --global_seed 111 --agent gsca
python3 -m urban_planning.eval --cfg hlg --global_seed 111 --agent ga

在demo脚本中我试图使用plan.p获得gdf数据，是可行的：
![image](https://github.com/user-attachments/assets/e2f87d88-50d3-468f-9b41-0b3525da6eec)

我这样理解不知是否正确：
1.每次training过程都会获得一个model文件（best.p），这个最佳结果也是检查点，可以用于恢复训练或被用来生成具体的plan
2.每次eval过程都会获得一个plan文件（plan.p）,此文件只是用来分析智能体在不同环境下的决策行为？

期待您的回答！

**Comment by gallexy-liu** [comment]
是的，你已经拿到了gdf，用下面的方法就可以操作了
env.load_plan(gdf)
env.score_plan()
env.visualize()

**Comment by Kevin-Lee1299** [comment]
请问下上面的best.p和plan.p的具体区别是什么呢？
我这样理解不知是否正确：
1.每次training过程都会获得一个model文件（best.p），这个最佳结果也是检查点，可以用于恢复训练或被用来生成具体的plan
2.每次eval过程都会获得一个plan文件（plan.p）,此文件只是用来分析智能体在不同环境下的决策行为？

十分期待您的回答！

**Comment by gallexy-liu** [comment]
train_ga.py得到的best.p比较特别，里面没有真正的plan信息，train.py不一样，试一下就知道了
