### ISSUE TITLE
CRS not set for some of the concatenation inputs.

### ISSUE THREAD

**Issue by Kevin-Lee1299** [tsinghua-fib-lab/DRL-urban-planning#19]
there is always a warning when i run the the training script and evaluate script：
UserWarning: CRS not set for some of the concatenation inputs. Setting output's CRS as unknown (the single non-null crs provided).
![image](https://github.com/user-attachments/assets/c6750163-1963-4f6b-87b2-427b53d0bb05)

Will this warning have a negative impact on the final result? 
How can I avoid this warning?

**Comment by gallexy-liu** [comment]
库版本问题，大概是geopandas库，改成0.11.1 就行。或者命令行 -w ignore 去掉

**Comment by gallexy** [comment]
这样处理使用高版本库终究是一个问题，最好能在代码层面处理掉

**Comment by gallexy-liu** [comment]
![image](https://github.com/user-attachments/assets/bd4acdab-a471-43e7-b2cb-9e377cba70c6)
找到了，在 plan_client.py的restore_plan里设置crs即可
