### ISSUE TITLE
policy network outputs a action whose value on land_use_mask is 0

### ISSUE THREAD

**Issue by gdjmck** [tsinghua-fib-lab/DRL-urban-planning#3]
In _agent.py_ module, after a _action_ is sampled from _select_action()_ method, the action was passed to the _env.step_ method.
Inside _env.step()_ method, _self._current_land_use_mask_ object is used to filter unreasonable positions by _self._current_land_use_mask[action] == 0_, and if it was 0 and throws a InfeasibleActionError.

My question is there is no guarentee that the action would not fall into _self._current_land_use_mask_ with values of 0, and the training would stop for this exception. Was it a problem or should I just not raise the exception and replace it with a random choice of valid position in _self._current_land_use_mask_?

**Comment by DavyMorgan** [comment]
Thanks for your question. In the observation, there is an action mask indicating which action is feasible. And when sampling actions from the policy network, we set the selection probability according to the action mask. Please check these two lines of codes:
[land use](https://github.com/tsinghua-fib-lab/DRL-urban-planning/blob/ec5bd0a765ec91c82bab3a6736ae2bc8e048dcd1/urban_planning/models/policy.py#L51)
[road](https://github.com/tsinghua-fib-lab/DRL-urban-planning/blob/ec5bd0a765ec91c82bab3a6736ae2bc8e048dcd1/urban_planning/models/policy.py#L60)

Therefore, the policy network will actually never output infeasible actions. Here the InfeasibleActionError is left for debugging.
