### ISSUE TITLE
Question about the model transferability

### ISSUE THREAD

**Issue by Sabrina2040** [tsinghua-fib-lab/DRL-urban-planning#5]
The overall idea of the code is also very clear. But I have one question about the embodiment of model transferability within the code. I don't seem to find any code that embodies the training process related to model transferability? Or is it that different types of community environments can be switched directly without making other types of modifications, such as dimensions of action outputs, etc. I envision that the number of edges and points in the graphs they compose are different for different sized communities, so there needs to be some code additions(either fine-tuning or re-training) in the current version of the repo.

**Comment by DavyMorgan** [comment]
Thanks, we use finetuning to achieve transfer across different communities.

Specifically, we pretrain a model on a 3x3 grid community, and finetune the model on other communities. To achieve the finetuning, you just need to change the cfg file and set the iteration cmd param to a specified iteration. Please refer to the flags in train,py:
`flags.DEFINE_string('iteration', '0', 'The start iteration. Can be number or best. If not 0, the agent will load from '
                                      'a saved checkpoint.')`
