### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by AlterHoodie** [tsinghua-fib-lab/DRL-urban-planning#9]
While trying to run Your Project `python -m urban_planning.train --cfg hlg --global_seed 111` Iam running into this error ` TypeError: cannot pickle '_thread.lock' object` 
![image](https://github.com/tsinghua-fib-lab/DRL-urban-planning/assets/106602542/a1ad99cf-596d-49f0-bfe5-9a64a686efbb)

Iam running the project in Windows, Python - 3.8
Is this a windows issue since your Test OS Environment is Linux

**Comment by DavyMorgan** [comment]
Yes, the multiprocess implementation currently only supports Linux-based OS.

**Comment by AlterHoodie** [comment]
Ahh ok, Thank you very much.
